name: json_by_path
description: Get, Set, create, delete Json Maps using path relative keys. No
  dependencies, as simple as possible!
version: 0.0.2-beta

# homepage: https://www.example.com
repository: https://github.com/GnRSlash/json_by_path
issue_tracker: https://github.com/GnRSlash/json_by_path/issues

environment:
  sdk: '>=2.15.0-134.5.beta <3.0.0'

# dependencies:
#   path: ^1.8.0
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies:
  
